//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phonexis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phonexis.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application helps find YouTube video links based on song titles provided in a text file..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies used: .NET 6.0, WPF, SQLite, YouTube Data API v3..
        /// </summary>
        public static string AboutTechnology {
            get {
                return ResourceManager.GetString("AboutTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Phonexis.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Calls Today.
        /// </summary>
        public static string ApiCallsToday {
            get {
                return ResourceManager.GetString("ApiCallsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Calls Used: {0}.
        /// </summary>
        public static string ApiCounterLabel {
            get {
                return ResourceManager.GetString("ApiCounterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key Error.
        /// </summary>
        public static string ApiKeySetErrorTitle {
            get {
                return ResourceManager.GetString("ApiKeySetErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid API keys entered..
        /// </summary>
        public static string ApiKeySetErrorMessage {
            get {
                return ResourceManager.GetString("ApiKeySetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Keys Set.
        /// </summary>
        public static string ApiKeySetSuccessTitle {
            get {
                return ResourceManager.GetString("ApiKeySetSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set {0} API keys..
        /// </summary>
        public static string ApiKeySetSuccessMessage {
            get {
                return ResourceManager.GetString("ApiKeySetSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse TXT File....
        /// </summary>
        public static string BrowseMenuItem {
            get {
                return ResourceManager.GetString("BrowseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Only Mode.
        /// </summary>
        public static string CacheOnlyMode {
            get {
                return ResourceManager.GetString("CacheOnlyMode", resourceCulture);
            }
        }
/// <summary>
        ///   Looks up a localized string similar to Only use results already present in the local cache.
        /// </summary>
        public static string CacheOnlyModeDescription {
            get {
                return ResourceManager.GetString("CacheOnlyModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change API Key.
        /// </summary>
        public static string ChangeApiKey {
            get {
                return ResourceManager.GetString("ChangeApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the cache? All cached search results and thumbnails will be deleted..
        /// </summary>
        public static string ClearCacheConfirmMessage {
            get {
                return ResourceManager.GetString("ClearCacheConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache Confirmation.
        /// </summary>
        public static string ClearCacheConfirmTitle {
            get {
                return ResourceManager.GetString("ClearCacheConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error clearing cache..
        /// </summary>
        public static string ClearCacheErrorMessage {
            get {
                return ResourceManager.GetString("ClearCacheErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared successfully..
        /// </summary>
        public static string ClearCacheSuccessMessage {
            get {
                return ResourceManager.GetString("ClearCacheSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Cleared.
        /// </summary>
        public static string ClearCacheSuccessTitle {
            get {
                return ResourceManager.GetString("ClearCacheSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 TX-Breaker. All rights reserved..
        /// </summary>
        public static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create TXT.
        /// </summary>
        public static string CreateTXT {
            get {
                return ResourceManager.GetString("CreateTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create TXT from Audio....
        /// </summary>
        public static string CreateTxtMenuItem {
            get {
                return ResourceManager.GetString("CreateTxtMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Current Query.
        /// </summary>
        public static string EditQueryMenuItem {
            get {
                return ResourceManager.GetString("EditQueryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Query.
        /// </summary>
        public static string EditQueryButton {
            get {
                return ResourceManager.GetString("EditQueryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Query.
        /// </summary>
        public static string EditQueryDialogTitle {
            get {
                return ResourceManager.GetString("EditQueryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the search query:.
        /// </summary>
        public static string EditQueryDialogLabel {
            get {
                return ResourceManager.GetString("EditQueryDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMenuItem {
            get {
                return ResourceManager.GetString("ExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBackButton {
            get {
                return ResourceManager.GetString("GoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonexis - TXT a YT Multisearch.
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoTab {
            get {
                return ResourceManager.GetString("InfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key set.
        /// </summary>
        public static string NoApiKeySet {
            get {
                return ResourceManager.GetString("NoApiKeySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API keys configured. Would you like to set them now?.
        /// </summary>
        public static string NoApiKeysMessage {
            get {
                return ResourceManager.GetString("NoApiKeysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API Keys.
        /// </summary>
        public static string NoApiKeysTitle {
            get {
                return ResourceManager.GetString("NoApiKeysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start search without API keys or Test Mode enabled..
        /// </summary>
        public static string NoApiKeysError {
            get {
                return ResourceManager.GetString("NoApiKeysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No links to save..
        /// </summary>
        public static string NoLinksToSaveMessage {
            get {
                return ResourceManager.GetString("NoLinksToSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved state found to restore..
        /// </summary>
        public static string NoSavedStateMessage {
            get {
                return ResourceManager.GetString("NoSavedStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Saved State.
        /// </summary>
        public static string NoSavedStateTitle {
            get {
                return ResourceManager.GetString("NoSavedStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No songs found in the selected file..
        /// </summary>
        public static string NoSongsMessage {
            get {
                return ResourceManager.GetString("NoSongsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Songs Found.
        /// </summary>
        public static string NoSongsTitle {
            get {
                return ResourceManager.GetString("NoSongsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Results.
        /// </summary>
        public static string RefreshResultsButton {
            get {
                return ResourceManager.GetString("RefreshResultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Session.
        /// </summary>
        public static string ResumeStateMenuItem {
            get {
                return ResourceManager.GetString("ResumeStateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ResumeStateButton {
            get {
                return ResourceManager.GetString("ResumeStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save links to file.
        /// </summary>
        public static string SaveLinksDialogTitle {
            get {
                return ResourceManager.GetString("SaveLinksDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving links: {0}.
        /// </summary>
        public static string SaveLinksError {
            get {
                return ResourceManager.GetString("SaveLinksError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0} links to file {1}.
        /// </summary>
        public static string SaveLinksSuccessMessage {
            get {
                return ResourceManager.GetString("SaveLinksSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Complete.
        /// </summary>
        public static string SaveLinksSuccessTitle {
            get {
                return ResourceManager.GetString("SaveLinksSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Session.
        /// </summary>
        public static string SaveStateMenuItem {
            get {
                return ResourceManager.GetString("SaveStateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveStateButton {
            get {
                return ResourceManager.GetString("SaveStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TXT File.
        /// </summary>
        public static string SelectFileLabelDefault {
            get {
                return ResourceManager.GetString("SelectFileLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        public static string SelectFileLabelSelected {
            get {
                return ResourceManager.GetString("SelectFileLabelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set API Keys.
        /// </summary>
        public static string SetApiKeyDialogTitle {
            get {
                return ResourceManager.GetString("SetApiKeyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter YouTube API keys separated by commas:.
        /// </summary>
        public static string SetApiKeyDialogLabel {
            get {
                return ResourceManager.GetString("SetApiKeyDialogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string SettingsMenuItem {
            get {
                return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Song.
        /// </summary>
        public static string SkipSongButton {
            get {
                return ResourceManager.GetString("SkipSongButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string StartOverMenuItem {
            get {
                return ResourceManager.GetString("StartOverMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string StartOverButton {
            get {
                return ResourceManager.GetString("StartOverButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start over? All progress will be lost..
        /// </summary>
        public static string StartOverMessage {
            get {
                return ResourceManager.GetString("StartOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string StartOverTitle {
            get {
                return ResourceManager.GetString("StartOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarted.
        /// </summary>
        public static string StartOverConfirmTitle {
            get {
                return ResourceManager.GetString("StartOverConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been reset. You can start over..
        /// </summary>
        public static string StartOverConfirmMessage {
            get {
                return ResourceManager.GetString("StartOverConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Search.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the application state..
        /// </summary>
        public static string StateSaveError {
            get {
                return ResourceManager.GetString("StateSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application state saved successfully..
        /// </summary>
        public static string StateSavedMessage {
            get {
                return ResourceManager.GetString("StateSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Saved.
        /// </summary>
        public static string StateSavedTitle {
            get {
                return ResourceManager.GetString("StateSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid state found to restore. Select a text file to begin..
        /// </summary>
        public static string StateRestoreInvalidMessage {
            get {
                return ResourceManager.GetString("StateRestoreInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous state restored successfully.\n\nFile: {0}\nCurrent Position: {1} of {2}\nSelected Links: {3}.
        /// </summary>
        public static string StateRestoredMessage {
            get {
                return ResourceManager.GetString("StateRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Restored.
        /// </summary>
        public static string StateRestoredTitle {
            get {
                return ResourceManager.GetString("StateRestoredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Error.
        /// </summary>
        public static string StateRestoreErrorTitle {
            get {
                return ResourceManager.GetString("StateRestoreErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mode.
        /// </summary>
        public static string TestMode {
            get {
                return ResourceManager.GetString("TestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonexis - TXT a YT Multisearch.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
